name: typewritertext
description: A simple typewriter text animation wrapper for flutter. Supports iOS, Android, web, Windows, macOS, and Linux.
version: 2.3.0
homepage: https://github.com/Nialixus/typewritertext.git
funding: 
  - https://www.buymeacoffee.com/nialixus
screenshots:
  - description: 'TypeWriter Dall-E Logo'
    path: logo.png
topics:
  - utility

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: null